name: validate-pr-markdown
run-name: Validate pull request Markdown files from @${{ github.actor }}
on: pull_request
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run-tests:
    name: Run Test Files
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout to Repository
        uses: actions/checkout@v2
      - name: Run test files
        run: make test
